- lib/layer.py
- lib/tiledsurface.py
A tentative fix for https://github.com/mypaint/mypaint/issues/145.
Tentative because I'm not sure what a "background tile" is or how that would affect the fixing of this issue.
I found another trim() function in lib/strokemap.py when I grepped for 'Only complete tiles'. Am I correct in thinking that that's a separate problem?
> zero pixels outside of the frame when trimming

- mypaint.py
Addresses issue #65 and also tweaks wording a bit to better reflect what conforming to the XDG basedir spec means.
I personally am okay with such a message being info, because I like putting my stuff in $XDG_{CONFIG,DATA}_HOME whenever possible and in theory this message would have told me that I could move mypaint configs into those directories (in practice it got buried in GTK warning messages).
This is outside the scope of this issue, but it also wouldn't hurt to add something to a README about what needs to move where if you want to migrate to $XDG_{CONFIG,DATA}_HOME.
> make it clear when the old configuration area is being used

- lib/pixbuf.py
Prevent the following bug when opening any file : 
```
Traceback (most recent call last):
File "/usr/local/share/mypaint/gui/filehandling.py", line 446, in open_cb
self.open_file(dialog.get_filename().decode('utf-8'))
File "/usr/local/share/mypaint/gui/drawwindow.py", line 79, in wrapper
func(self, *args, **kwargs)
File "/usr/local/share/mypaint/gui/filehandling.py", line 264, in open_file
self.doc.model.load(filename, feedback_cb=self.gtk_main_tick)
File "/usr/local/share/mypaint/lib/document.py", line 764, in load
load(filename, **kwargs)
File "/usr/local/share/mypaint/lib/document.py", line 823, in load_from_pixbuf_file
pixbuf = lib.pixbuf.load_from_file(filename, feedback_cb)
File "/usr/local/share/mypaint/lib/pixbuf.py", line 76, in load_from_file
pixbuf = …
```
> Fix the "NameError: global name 'lib' is not defined" error from pixbuf.py

- gui/buttonmap.py
- gui/document.py
This should fix issue #146.
Tested saving preferences, adding new shortcuts, removing existing shortcuts and the shortcut cheatsheet thing that appears in the bottom right corner of the window ("With Ctrl held down...").
Spun up mypaint with a french locale as well. Modifier keys (ctrl, alt, shift) are being translated by gtk.accelerator_get_label(). Button/Btn will need support in po/, but if strings like "Button1" already have a translation, then it should be pretty easy to do even if you don't speak the language in question.
> Use localized strings for key bindings in prefs dialog

- gui/gtkexcepthook.py
The version number in the crash log now includes the build date, and
the git version. This should make it easier to find out which git
versions are affecty by the reported issue.
> Version Call in the Crash Log Change

- gui/filehandling.py
- lib/document.py
- lib/layer.py
For issue #165. The parameter that governed whether or not blit_tile_into() kept the background in or not was inconsistently named (it was 'background' in half the source code, and 'render_background' in the other half). I suspect the regression made its way in because it's...nontrivial to keep track of all the parameters weaving in and out of kwargs/options on the way from gui/filehandling.py to lib/fastpng.hpp.
> Correctly handle PNG transparency when saving

- gui/drawutils.py
- gui/previewwindow.py
I was a bit concerned about what the cairo path juggling in the new `draw_draggable_path_drop_shadow()` would mean for performance, though it doesn't seem noticeably slower on my machine.
The extra `math.ceil` calls are there because there are occasional rendering artifacts without them. I'm not really sure what they actually fix, since I thought that rounding protection was what the `+ 4` was for.
I also wanted to have a chat about when/if the viewfinder frame should change colour. I think it makes sense to have it turn the active colour (yellow) when it's hovered over and while it's being dragged. But what about when a user is zooming/rotating through the canvas?
> Viewfinder style change

- gui/stategroup.py
Based off of Loentar's original patch.
Closes #86.
> Eat double and triple clicks to avoid a programming error.

- gui/colorpicker.py
- gui/document.py
- gui/layermanip.py
- gui/mode.py
- gui/viewmanip.py
Where "movement tools" means Move Layer, Pan View, Zoom View or Rotate
View modes. Addresses mypaint/mypaint#87.
Allow the popup menu to be brought up while in the above three modes
Fix a small typo in a comment in gui/mode.py
> Do not deselect movement tools after one use

- gui/brushmanager.py
- gui/brushselectionwindow.py
- gui/dialogs.py
- gui/pixbuflist.py
- gui/toolbar.py
Starting with add to favourites, remove from favourites, copy, delete
and a placeholder for edit. I also noticed that the recently used list in the toolbar window doesn't respond to right clicks.
This is a WIP that needs more testing. **use a separate throwaway config area for this. It was eating brush groups every launch until I fixed something, and I'm not totally convinced the code is bulletproof yet.**
Partial list of things that I've tried:
* copy brush, restart mypaint
* copy brush, copy its copy, restart mypaint
* copy brush, switch group, switch back, delete copy, restart mypaint
* delete brush, restart mypaint
* favourite brush, restart mypaint
* copy brush, favourite copy, delete copy, restart mypaint
Also would appreciate feedback on the naming of the menu options.
Addresses …
> Add right click menu to brushes

- lib/helpers.py
I don't usually have access to any OSX machines, so it'd be cool if someone with a Mac tested this out. Naming the directory 'MyPaint' seems to blend in better, but may cause headaches down the road. I can change that to 'mypaint' if it seems like it would cause too much trouble.
As for the Linux-y changes...how many applications actually use `~/.thumbnails` these days? Does anybody actually prefer using it to following the thumbnail spec? Is it better to just create `$XDG_CACHE_HOME/thumbnails` or `~/.cache/thumbnails` if needed?
> Use native cache directories for thumbnails in Linux and Mac OS X

- gui/gtkexcepthook.py
I guess the new buttons could also go right above details (and would probably help with the peculiar linewrapping), but I feel like that's maybe kind of weird for a dialog window.
It looks like someone intended the trace to be printed out in monospace, but it wasn't doing that for me. Fixed for me now, though I can't tell if I've now broken it for other versions of...pygtk? pango?
A first stab at #232.
> Better crash dialog

- gui/colors/hsvsquare.py
This one's just a minor fix for swapping the tooltip labels around in HSV Square. ^^;
> Found the tooltips applied to the wrong places in HSV Square

- gui/layers.py
Otherwise unknown causes can make them disappear.
The columns are "Visibility", "Lock" and "Type".
Addresses mypaint/mypaint#414.
> layers panel: add explicit width constraint to columns

- gui/colorpicker.py
In older versions of mypaint, it was possible to pick a color by simply
holding down the 'pick color' hotkey and hovering over a color. At some
point, this changed. Users were now required to hold down the hotkey and
then drag over the color. This patch restores the old behaviour.
Resolves mypaint/mypaint#253.
> Restore old color picker behaviour (hover to pick)

- gui/document.py
All mode-flip actions are currently being sent to the main document. This
causes issues such as mypaint/mypaint#272. It also makes it impossible to
use other tools (such as line-drawing tools) on the scratchpad. With this
patch, mode-flip actions are sent to the active document instead.
Note that this does not completely solve issue mypaint/mypaint#272, since
it is still impossible to use the eyedropper on the scratchpad by clicking on
the toolbar.
> Dispatch mode-flip actions to the active document

- gui/backgroundwindow.py
Possible fix for issue #512:
Simply don't set the background to the window when loading the background chooser dialog.
Normally the background of the paintings is loaded somewhere else (for example in application.py).
Maybe I am overlooking something and this solution is too simplistic?
> Fix issue 512

- gui/menu.xml
- gui/resources.xml
Changing accelerator keys under GTK no longer requires individual menu
entries for each option, so the Current Tool submenu is unnecessary.
Closes mypaint/mypaint#613
> Edit menu: remove unnecessary Current Tool entries

- gui/resources.xml
Readded tooltips for the RotateLeft and RotateRight actions that
were removed in #553.
Closes mypaint/mypaint#554
> RotateLeft and RotateRight actions: added tooltips

- gui/application.py
Since TiledDrawWidget._size_allocate_cb() calculates offsets relative to the coordinates of the main window, it can be used only with the main viewport. 
Fixes mypaint/mypaint#597. You can easily reveal the problem by drawing something in the scratchpad and then resizing the main window.
> Scratchpad: Don't scroll on "size-allocate".

- gui/topbar.py
- gui/windowing.py
PyGI in addition returns a useless integer (the result of
gdk_window_get_origin()).
See:
https://developer.gnome.org/gdk3/stable/gdk3-Windows.html
pygtkcompat/pygtkcompat.py
> Fix PyGTK-style Gdk.Window.get_origin().

- gui/filehandling.py
Hey @achadwick,
- I have changed the title of the Export dialog box 
- Modified the init_save_dialog() method to return a one-time dialog as you mentioned in the comment of mypaint/mypaint#399
- But I am not sure what you meant by "And check out the try: finally: mess on the end. Looks like there's an old GTK bug we're working around" in the same comment. Did you want me to remove that workaround to see if that GTK bug still exists?
> Export dialog retitled (mypaint/mypaint#399)

- gui/brushselectionwindow.py
- gui/colors/adjbases.py
Gtk.drag_set_icon_pixbuf() is the right way to set the D&D icon
dynamically from the "drag-begin" event. drag_source_set_icon_pixbuf()
should be used to set a "static" icon.
In theory, they should work equally, but I noticed that icon set via
drag_source_set_icon_pixbuf() is not visible if its size is greater
than 55px (as in the brush list). Maybe it's a bug in GTK+ or
something desktop-specific (XFCE), but anyway it's better to use
the "right" way.
Examples from the GTK+ sources:
[gtk_drag_set_icon_pixbuf](https://github.com/GNOME/gtk/search?utf8=%E2%9C%93&q=gtk_drag_set_icon_pixbuf&type=Code)
[gtk_drag_source_set_icon_pixbuf](https://github.com/GNOME/gtk/search?utf8=%E2%9C%93&q=gtk_drag_source_set_icon_pixbuf&type=Code)
> Replace Gtk.Widget.drag_source_set_icon_pixbuf() with Gtk.drag_set_icon_pixbuf()

- gui/backgroundwindow.py
In Python 2, int(x) / int(y) always returns 0 if y > x.
> BackgroundList: Fix preview scale factor.

- gui/colors/hcywheel.py
- gui/displayfilter.py
- gui/drawutils.py
- gui/freehand.py
- gui/inktool.py
- gui/tileddrawwidget.py
- lib/SConscript
- lib/color.py
- lib/document.py
- lib/fileutils.py
- lib/helpers.py
- lib/layer/group.py
- lib/layer/tree.py
- lib/pixbufsurface.py
- lib/stroke.py
- lib/strokemap.py
- lib/surface.py
- lib/tiledsurface.py
- tests/guicontrol.py
- tests/test_compositeops.py
- tests/test_memory_leak.py
- tests/test_mypaintlib.py
- tests/test_performance.py
The convention is `import numpy as np`, so use that instead of the various other forms.
> Standardize NumPy imports

- mypaint.py
There is no printing here, and the automatic version generation inserts
code at the beginning of the file, thus breaking with the __future__
import.
Fixes #695.
> py3k: Remove __future__ import from main script.

- lib/layer/tree.py
With a frame like 10x1000px, the smaller scaled side becomes zero, and `pixbufsurface.Surface` raises an assertion error.
> RootLayerStack.render_thumbnail: Ensure that the smaller side is > 0.

- gui/accelmap.py
- gui/document.py
- gui/resources.xml
Pan Left, Pan Right, Pan Down and Pan Up used to be hardcoded into the arrow keys. I find this really awkward, as I need to pan often, my shortcut hand is sitting in the opposite side of the keyboard, and the spacebar option is a three step process my brain refuses to get used to. (Hit space, pan, hit space again.)
This commit allows the user to customize the four directional pan actions.
Objections?
Please review this change in particular:
https://github.com/ydahhrk/mypaint/commit/a165e6ab1275da0d4debf507ec2d235803ef8514#diff-43086ad29962d3495933ef1c3bc3ad5bL400
> Pan shortcuts: allow user to customize keys.

- README_WINDOWS.md
The commands for installing dependencies and
building mypaint contained a typo in the
msys2-build.sh file name.
> ReadMe (Windows): Fix typo in commandlines

- gui/brushselectionwindow.py
- gui/quickchoice.py
The brush selection window shows the tooltip, but it was not shown in
the quickchoice selector (default keyed to B) before. This commit
improves brush selection experience.
The existing brush id/icon/tooltip functions in brushselectionwindow
were made public.
Closes mypaint/mypaint#702.
> quickchoice: Show brush description in tooltip

- desktop/mypaint-ora-thumbnailer.py
- gui/application.py
- gui/brusheditor.py
- gui/brushmanager.py
- gui/colors/paletteview.py
- gui/drawutils.py
- gui/drawwindow.py
- lib/brushes_migrate_json.py
- lib/helpers.py
- lib/layer/data.py
- lib/layer/tree.py
- lib/palette.py
- lib/pixbuf.py
- lib/surface.py
- svg/symbolic-icons-extract.py
- tests/test_memory_leak.py
- tests/test_mypaintlib.py
- tests/test_performance.py
Using a context manager ensures that the file will be closed regardless of any exceptions that might occur. The only file that doesn't work this way is the logger output.
> Ensure open files are closed using context managers

- gui/document.py
- gui/menu.xml
- gui/resources.xml
Added, changed, and edited the default shortcuts and tooltips for MyPaint. Also removed the RevealLayersTool, and similar objects and replaced them with their Toggle versions. Lastly, I've added the shortcuts for the Inking Tool.
> New Keybaord Shortcuts and Defaults

- gui/document.py
- gui/symmetry.py
- lib/document.py
- lib/helpers.py
- lib/layer/core.py
- lib/layer/data.py
- lib/layer/tree.py
- lib/tiledsurface.hpp
- lib/tiledsurface.py
Implements #529 .
The reason why the [RFC] is in the pull request title is that I was working on getting this into a presentable, working state before asking for comments on the implementation.
The following commits implement horizontal, horizontal + vertical, rotational, and snowflake symmetry.
That being said, I'm fairly happy with how I implemented the UI. It's mostly straightforward.
I'm just confused at how I should handle the spinbox for the rotational symmetry lines. Without me adjusting the code for the alternative symmetry modes, the dialog box for mypaint's symmetry X axis isn't insensitive when symmetry is disabled. Is this intended? If not, I'll adjust the symmetry UI code to respond properly when symmetry is disabled.
Further commits here are likely going to be stylistic …
> [RFC] Alternative symmetry modes

- windows/msys2-build.sh
Build and install libmypaint from source. This will ensure the latest commits from each git repository can work together.
> Tea-CI: Build libmypaint from Source.

- gui/colors/hcywheel.py
Use Gdk.Cursor.new_for_display on realize instead.
Backported from a larger patch by Daniel Plachotich.
Fixes #791
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859064
---
I haven't actually tried this with upstream version 1.2.1, but I got the same traceback as in #791 with a Debian package that cherry-picked 48a43f9 and d9eaec0 onto 1.2.0-4, and this fixed the issue there; so it seems a good candidate for a minimal backport.
> hcywheel: Avoid deprecated gdk.Cursor constructor

- gui/brushmanager.py
- gui/fill.py
- gui/mode.py
MyPaint now remembers the last used brush-based tool, so when the user chooses a new brush (via a shortcut or whatever), the active tool becomes something relevant.
> Mode stack: Add layer for brush tools

- gui/curve.py
The limit of 8 points is a bit too restrictive, preventing
you from making stair-stepped or other interesting patterns
that are especially useful for stroke, anti-art offsets, gridmap, etc.
This patch requires the corresponding patch to libmypaint.
I've added 64 points, and made the grid 10x10 instead of 4x4.
Also, the points snap on 0.05 instead of 0.25
> Curve points

- gui/drawutils.py
- gui/freehand.py
- gui/inktool.py
- gui/linemode.py
- gui/mode.py
- lib/brush.hpp
- lib/command.py
- lib/layer/data.py
- lib/python_brush.hpp
- lib/stroke.py
This is the GUI counterpart to libmypaint changes to correct brushes for view rotation and zoom:
https://github.com/mypaint/libmypaint/pull/70
> Brush inputs/settings calibrated for viewzoom and viewrotation [WIP]

- SConscript
- SConstruct
- lib/SConscript
using different notation for ocatal numbers,
using brackets for print()
using 'in' instead of dropped has_key
all changes are backward compatible (tested with python-2.6.9)
helps with #392 
Background: python2 will be discontinued in 2020 thus we are pushing it out of openSUSE Tumbleweed now, which causes build failures with the mypaint package now.
> Port SCons files to python3

- gui/freehand.py
This opens up a lot more keys to control settings
like hue, sat, brightness while painting in real-time
Needs more testing, but no obviously horrible side effects yet.  It can be annoying if you are trying to use the color adjuster keys (Shift+a,s,d,f,q,w) and draw at the same time, since if you lift the pen up it will jump into line-mode.  However, I think for the people that might use this feature they will figure out pretty quick to either remap all the color adjusters, or just remove the shift+button1=line mode mapping.
IMO using naked modifers+button1 is just a bad idea, although I know it's been done for the past 30 years so it's sort of baked into people's workflow.  So, I don't know if we could remove these defaults without causing a lot of grief.
Closes #852
> Allow modifiers while painting 

- desktop/mypaint.appdata.xml
This updates the AppStream metadata to a newer version, and fixes all compatibility problems detected by `appstreamcli validate gramps.appdata.xml`:
```
E - mypaint.appdata.xml:mypaint.desktop:7
The summary tag must not contain tabs or linebreaks.
I - mypaint.appdata.xml:mypaint.desktop:27
Consider using a secure (HTTPS) URL for 'http://mypaint.org/'
W - mypaint.appdata.xml:mypaint.desktop:5
The component ID is not a reverse domain-name. Please update the ID and that of 
the accompanying .desktop file to follow the latest version of the Desktop-Entry 
and AppStream specifications and avoid future issues.
E - mypaint.appdata.xml:mypaint.desktop:29
The screenshot does not contain any images.
I - mypaint.appdata.xml:mypaint.desktop:5
The id tag for "mypaint.desktop" still contains a 'type' …
```
> Fix AppStream metadata validation

- setup.py
Metainfo files should be installed into /usr/share/metainfo.
> Don't use legacy path for AppStream metainfo file

- README.md
- gui/application.py
- gui/document.py
- gui/freehand.py
- gui/resources.xml
- setup.py
Instead of sending 0.5 pressure for
devices that don't support it, we can
send any pressure  and rotation we want
via sliders and hotkeys.  This opens up a lot
of expression for users with mice or other
unsupported devices.   Many brushes change
several settings via pressure, such as smudge.
So changing opacity alone is not a substitute.
Also, this may be unpopular, but it is time
to free up modifiers shift, control, and alt.
Having these free allows us to re-use keys
to support on-the-fly brush adjustments like
changing colors, size, opacity, etc, while
mid-stroke.
> Real Fake Pressure and Barrel Rotation

- lib/fill_common.py
- lib/floodfill.py
Replace the numpy.full array creation call with a function
that should be compatible with any numpy >= 1.3
Closes #1009
> Floodfill: replace call dependent on numpy 1.10

- gui/document.py
- gui/layerswindow.py
- gui/preferenceswindow.glade
- gui/preferenceswindow.py
Although the feature of showing the selected layer in isolation for a short time is often useful, for my own part I find it impairs more than it helps when jumping frequently between different layers while working on them (0.8 seconds is a bit too long for my taste).
This patch simply adds an option to disable the blinking, with the default being the current behaviour.
> Add option for disabling layer blinking upon layer creation/selection

- BUILDING.md
- gui/meta.py
- lib/fix15.hpp
- setup.py
Only non-functional changes from a user-facing perspective.
Fixes double escaping in About window.
Split up python2/3-specific dependencies in build instructions.
Fix build sub_commands order to allow demo to run immediately from a fresh build.
New option to build_ext allows building mypaintlib with rpath's set directly from the pkg-config library dirs,
allowing not only easier local installs, but also building and running demos against different versions of libmypaint during development.
Added (more explicit) instructions for how to build/install/run MyPaint in local directories.
> Fix About window text glitch, add new build instructions and a new build_ext option

- BUILDING.md
- doc/PERFORMANCE
- doc/spectral/spectral.md
- gui/autorecover.glade
- gui/blendmodehandler.py
- gui/fill.py
- gui/layerprops.glade
- gui/picker.py
- gui/profiling.py
- lib/compositing.hpp
- lib/fill/floodfill.cpp
- lib/layer/__init__.py
- lib/morphology.py
- lib/palette.py
- po/SConscript
- po/update_potfiles.sh
Found via `codespell -i 3 -w -S *.po -L hist,od`
> Fix mIsc.  typos

- setup.py
Locale files have not been part of the windows build artifacts since June 2017.
This is due to the install command (rightly) using --skip-build, which in turn means that the locale data paths are not set (leading to the locales not being installed).
The simple fix is to just add `build_translations` before `install` in the PKGBUILD file, but I think it's better to fix the underlying bug.
Additionally, the calls to pkg-config and msgfmt are altered to allow packagers to adjust the program names via environment variables.
> Fix locales not being installed with --skip-build, make pkg-config/msgfmt configurable

- windows/msys2-build.sh
The appveyor windows build was failing after an msys2
package upgrade - the crucial change being that 'python'
now points to python3 instead of python2.
Invoke python2 explicitly instead of python, for now.
Moving forward, the build+deps should be switched to python3,
as python2 will be EOL in about five months.
I did not reinstate the pacman upgrade, as the updated msys2 base-installation makes it even less necessary (skipping it saves about 3½ minutes per arch.).
__Edit: I manually cancelled the travis build since only the appveyor build is affected by this change.__
> Fix appveyor build

- gui/application.py
- gui/brushmanager.py
- gui/compatibility.py
- gui/drawwindow.py
- gui/filehandling.py
- gui/fill.py
- gui/layers.py
- gui/layerswindow.py
- gui/preferenceswindow.glade
- gui/preferenceswindow.py
- gui/userconfig.py
- lib/brush.py
- lib/document.py
- lib/eotf.py
- lib/helpers.py
- lib/layer/core.py
- lib/layer/data.py
- lib/layer/group.py
- lib/layer/tree.py
- lib/meta.py
- lib/modes.py
- lib/pixbufsurface.py
- lib/pixops.cpp
- lib/tiledsurface.py
This adds support for the 1.x rendering and default settings, allowing pre-2.x files to be rendered consistently, albeit with worse support for the pigment features.
The compatibility mode for a document is written to the openraster file using a namespaced attribute, and can be changed by explicitly selecting a compatibility mode to open a file with (dropdown menu in file chooser dialog).
The commit messages describe the details quite comprehensively.
The majority of the new (non-glade) code is placed in the new gui.compatibility module, to avoid littering the existing modules with code that's only relevant to supporting old behavior.
> Backwards compatibility w. 1.x

- setup.py
rpath doesn't seem necessary for system installation but could be useful still.
> Enable rpath on BSD systems

- desktop/mypaint.appdata.xml
OARS is used by software stores to classify apps https://hughsie.github.io/oars/ this patch helps with a flathub requirement but is useful everywhere that appdata is used.
> Add OARS rating to appdata

- lib/pixops.cpp
Each load, save cycle introduced error while converting internal data to rgba8.
Errors were noticeable after a couple of saves.
It caused loss of color details and banding artifacts.
> Fix rounding in conversion to rgba8 while saving

- setup.py
Since we are already defining `_POSIX_C_SOURCE`, also define `_DARWIN_C_SOURCE` on Darwin to avoid a build error.
Closes #1086
> Define _DARWIN_C_SOURCE on Darwin

- gui/cursor.py
- gui/document.py
- gui/symmetry.py
- gui/tileddrawwidget.py
- lib/alg.py
- lib/document.py
- lib/layer/core.py
- lib/layer/data.py
- lib/layer/tree.py
- lib/tiledsurface.hpp
* Symmetry angle is now adjustable (though not directly on the canvas, yet)
* Rotational symmetry lines are drawn, instead of sharing drawing code with vertical+horizontal.
* Disable-button positioning reworked so that it indicates the symmetry center.
* Center-button added for unconstrained adjustment of symmetry center on the canvas.
A bunch of state bugs have also been fixed, including status bar message updates, active axis lines not always being marked as such, and some glitches when clearing documents (creating new docs, or opening file).
This patch **does not include** any (major) optimizations - **what remains** on that end is to:
* Remove redundant calculations.
* Only redraw the canvas area that has actually changed.
> Symmetry refactoring w. bug fixes and new features

- gui/picker.py
PyGTK Gdk.EventGrabBroken maps to the GdkEventGrabBroken struct which
does not have a time attribute. The invalid attribute was being passed
as an argument that had an appropriate default value, so the attribute
reference was removed, enabling the default value to be used instead.
Closes mypaint/mypaint#899
> Remove reference to non-existent Gdk.EventGrabBroken time attribute

- gui/autorecover.py
Problem was described by calsioro on community forum: https://community.mypaint.org/t/main-window-stays-dim-after-dismising-the-recover-backup-window/2573
> fix dimming of main window after dismissing recover backup window

- BUILDING.md
- mypaint.py
- setup.py
Instead of making assumptions about the structure, ~~there are now three explicit ways that paths to modules and resources are set up:~~
~~1. Static paths, set at install time, are used~~
~~2. Relative paths, with a fixed setup, are used (intended use case is for appimages and windows builds)~~
~~3. Paths relative to the source tree are used (like before, used for development).~~
the paths are now set up to be relative to the main script, at install time, and resolved at runtime. This approach will work for simple installs, as well as portable packages like the windows bundles and the appimage builds. It should also work fine for any reasonably sane use of `--root` `--prefix` and the `--install-xyz` directives.
The intention is for packagers to be able to configure the installation …
> Lib path refactoring

- svg/symbolic-icons-extract.py
There is a small typo in svg/symbolic-icons-extract.py.
Should read `retrieving` rather than `retrieveing`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, retrieveing -> retrieving

- lib/gettext_setup.py
- setup.py
- python 3 always open in universal mode, U is default mode in 3.0, and removed in 3.11
- mypaint doesn't use ld?n?gettext, so bind_textdomain_codeset isn't needed, that function is deprecated in 3.8 and is no-ops in 3.10 and removed in 3.11
> python: fix for Python 3.11

- BUILDING.md
Got setup.py working on OpenSUSE. Trudged through finding dependencies to get there, hoping to save others from the same effort.
> BUILDING.md: Added dependency instructions for OpenSUSE

- gui/brushmanip.py
- gui/buttonmap.py
- gui/colors/adjbases.py
- gui/colors/hcywheel.py
- gui/cursor.py
- gui/freehand.py
- gui/historypopup.py
- gui/layermanip.py
- gui/tileddrawwidget.py
- gui/widgets.py
- gui/windowing.py
Adwaita, the resident icon theme on GNOME removed the legacy X11 `circle` cursor: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/fb133a3989ee155c24201e30bab7dbc1c7c843fd
As a result, MyPaint would break when opening a file on GNOME systems.
Let’s use the equivalent `not-allowed` cursor from the XDG cursor-spec draft: https://www.freedesktop.org/wiki/Specifications/cursor-spec/
The circle cursor that was removed from Adwaita is in the fourth row, second column here: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/4d082e44e8361ca32360bb5b865be98a784ef4db/src/cursors/adwaita.svg
Here is the list of cursor constants supported by GDK 3 with images – it includes legacy X11 cursors: https://docs.gtk.org/gdk3/enum.CursorType.html
Here is the list of cursor names – only …
> Use standard cursor name

- BUILDING.md
- gui/brushmanager.py
On NixOS, exporting a brush group by pressing “Export as Zipped Brushset” action in its properties fails with:
ValueError: ZIP does not support timestamps before 1980
The `gui.brushmanager.BrushManager.export_group` doctest fails with the same error.
This is because Nix forces `mtime` of package files to 0 (1970-01-01) to ensure the build outputs are consistently reproducible.
Let’s disable strict timestamps to clamp the out-of-range timestamps to ZIP epoch. That argument was actually introduced in Python 3.8 because of reproducible builds: https://bugs.python.org/issue34097
This raises minimum version of Python to 3.8.
> Fix exporting brushes with mtime 0
