mypaint/mypaint

po/sk.po
=> Added slovak translation

po/en_CA.po
I'd like to point out some typos:
* [gui/externalapp.py:50](../blob/master/gui/externalapp.py#L50): `Mypaint` -> `MyPaint`
* [gui/linemode.py:768](../blob/master/gui/linemode.py#L768): `Elipses` -> `Ellipses`
* [gui/brusheditor.glade:756](../blob/master/gui/brusheditor.glade#L756) `Adjuist` -> `Adjust`
* [gui/resources.xml:1144](../blob/master/gui/resources.xml#L1144) `devies` -> `devices`
=> Update Canadian English translation.

gui/workspace.py
This closes mypaint/mypaint#412
=> Remember last active tab in each notebook

gui/application.py
In my testing environment I really had no $HOME/.config directory.
=> Use os.makedirs to create intermediate directories

gui/workspace.py
The problem is that when a widget is created, its parent Gtk.Container is already connected to the "size-allocate" signal of the parent Gtk.Widget. Excerpt from https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-size-allocate:
> This function is only used by GtkContainer subclasses, to assign a size and position to their child widgets.
The simple solution is to override do_size_allocate() so that our handler will be called first.
Another good thing is that the separator is now sticks when it's moved manually.
Fixes mypaint/mypaint#298.
=> ToolStack: Fix sticking of the last paned.

windows/README.md
Location of `mypaint.iss.in` moved to `/windows/innosetup/`
=> Location of `mypaint.iss.in` moved to `/windows/innosetup/`

gui/inputtestwindow.py
The window writes reports even after closing, making it hard to see other messages.
=> InputTestWindow: Stop reporting after closing.

gui/application.py, gui/backgroundwindow.py, gui/brushiconeditor.py, gui/brushmanager.py, gui/builderhacks.py, gui/buttonmap.py, gui/colors/hcywheel.py, gui/cursor.py, gui/device.py, gui/document.py, gui/freehand.py, gui/gtkexcepthook.py, gui/layers.py, gui/main.py, gui/quickchoice.py, gui/spinbox.py, gui/workspace.py, lib/alg.py, lib/brush.py, lib/document.py, lib/layer/tree.py, lib/meta.py, lib/tiledsurface.py, svg/symbolic-icons-extract.py, tests/test_compositeops.py, tests/test_memory_leak.py, tests/test_mypaintlib.py, tests/test_performance.py, tests/test_rendering.py
Most of stage 1 from [`futurize`](http://python-future.org/). I did not apply the `absolute_import` setting yet because mypaint is rife with relative imports and that would balloon this PR. Also, haven't fully reviewed the `division` setting yet.
These changes are confined to the files in which they actually make a difference. I will put blanket changes like enabling `print_function` across the code base in a separate PR where it will be easier to see just those changes.
This depends on #688 due to conflicts.
=> Python 3, stage 1 compatibility

lib/document.py
Currently, unless the frame is enabled, MyPaint saves files using an internal (dynamic) bounding box, which is always multiple by the tile size, and has (0, 0) coordinates. This is not the right way to do this. Let me explain using ORA as an example.
There are two backgrounds that MyPaint writes to ORA files:
* External, saved as a regular layer to be used by other software. This layer is just cropped using dimensions and coordinates of the dynamic bounding box. This can be OK when the background has no sensible borders (like a seamless canvas texture), but otherwise this is not what the user expects.
* Internal, to be used by MyPaint. This one has the right size (the size of the original image used as background), but since it's cropped from coordinates of the dynamic bounding box, it …
=> Use the right bounding box when saving a file

brushes/classic/coarse_bulk_1.myb, brushes/classic/coarse_bulk_2.myb, brushes/classic/ink_blot.myb, brushes/experimental/small_blot.myb, brushes/experimental/speed_blot.myb
Very few brushes used this setting.
=> viewzoom brush tweaks. Missed a few offset_by_speed.

README.md
Hey guys,
Long time lurker here! 
Been playing with mypaint for a while but never managed to do any contribution. 
Here is a small pr to do some cosometic changes in the readme. Hope I got it right. 
Thanks for the awesome app! 😄
=> fine tuned readme

lib/meta.py
=> Fix conversion of git version to str.

gui/mode.py
It could also use `Gdk.Cursor.new_for_display`, but I found it handy to use `self.doc.app.cursor.get_action_cursor`
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1555277
=> Load cursors in 'enter' handler

gui/workspace.py
does not affect hidden floating windows because those
might be really hard to find with a delay
closes #870
=> fullscreen UI: add 500ms delay to unhide edge panels on bump

gui/freehand.py, gui/inktool.py
Simplifies code and allows raw xtilt/ytilt values for inputs
Corresponding libmypaint PR: https://github.com/mypaint/libmypaint/pull/107
=> xtilt ytilt compensation moved to brush engine

gui/brushmanager.py, lib/i18n.py, lib/layer/group.py, mypaint.py
Four small crashers fixed - with the move-empty-group bug making the GUI virtually unusable rather than outright crashing.
=> Small crash fixes

.hound.yml
Only way I can find to test if the config works, without setting it up on my own clone.
=> Fix HoundCI config [skip ci]

.hound.yml, setup.cfg
=> Fix hound config [skip travis] [skip appveyor]

gui/linemode.py
Changes in line mode, allow moving ends of curve by pressing shift + ctrl.
=> Line mode - move ends of cruve

gui/colors/paletteview.py
button press event propagation was not working properly, so I added an `Gtk.EventBox()`.
=> Color Palette Bug : Fixed #922

gui/accelmap.py
=> Added the ability to filter keymaps.

gui/accelmap.py, gui/keyboard.py
Fixed a bug in the following image.
=> Keyboard Input Bug #974

setup.cfg, setup.py
=> setuptools fixes

gui/brushmanip.py, gui/buttonmap.py, gui/colors/adjbases.py, gui/colors/hcywheel.py, gui/cursor.py, gui/freehand.py, gui/historypopup.py, gui/layermanip.py, gui/tileddrawwidget.py, gui/widgets.py, gui/windowing.py
Hotfix to prevent developers accidentally working off of master (by making master the correct branch to work in)
=> Merge development into master

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/documentation.yaml
=> Point GitHub issue template COC link to mypaint.org
